project:
  type: manuscript

execute:
  freeze: auto
  include: false
  
code-links:
    - repo: noaa-afsc/ribbon-spotted-niche-partition

format:
  html: 
    theme: 
      - cosmo
      - custom.scss
    mainfont: "STIX Two Text"
    fontsize: 1.1em
    linestretch: 1.7
    toc: true
  docx: default
