project:
  type: manuscript

execute:
  freeze: auto
  include: false

callout-icon: false

format:
  html: 
    theme: 
      - cosmo
      - custom.scss
    mainfont: "STIX Two Text"
    fontsize: 1.1em
    linestretch: 1.5
    toc: true
  docx: default
  pdf: default
